language: php
dist: trusty
sudo: false

php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'
  - nightly

env:
  global:
    - secure: "HPrbKBgJTctoebpG/lBxPQ/6Jt0nqAYPG+G/9Qkvzbo5LS7XyCjfkARNY2aRvaOcaDo/RmyBx3OdxVXXVY/DxwlF0J/E1VoxD5w/lQOnOHGRK5CrH+L1ztLyp/mvQcI091oZgkAsJeeb7bQzyLXb/5ayFz2UKiYdIn2E7MpgjqI="

matrix:
  allow_failures:
    - php: nightly

services:
  - mysql
  - postgresql

cache:
  directories:
    - vendor

branches:
  only:
  - master
  - /^v\d/

notifications:
  email: false

# also see: test/setup_vendor.sh
before_script:
  - php -m
  - sh -c '[ -z $LOCALE_GEN ] || sudo locale-gen en_US.UTF-8 de_DE.UTF-8 fr_FR.UTF-8'
  - sh -c '[ -z $ENABLE_LDAP ] || phpenv config-add test/travis-ldap.ini'
  - test/travis_database.sh
  - test/setup_vendor.sh

script:
  # also see: modules/test/application/clicommands/PhpCommand.php
  - php phpcs.phar
  - php phpunit.phar -c modules/test/phpunit.xml --verbose

deploy:
  # Push to transifex
  - provider: script
    script: ./scripts/transifex-travis-push
    #on:
    #  branch: master
